In [1]:
import torch

In [18]:
def split_matrix(matrix):
    n = matrix.size(0)
    first_positive_index_matrix = torch.zeros_like(matrix)
    remaining_positive_indexes_matrix = matrix.clone()
    
    for i in range(n):
        row = matrix[i]
        pos_indices = torch.nonzero(row > 0).squeeze()
        if pos_indices.numel() > 1:
            first_pos_index = pos_indices[0].item()
            first_positive_index_matrix[i, first_pos_index] = matrix[i, first_pos_index]
            remaining_positive_indexes_matrix[i, first_pos_index] = 0
        else:
            remaining_positive_indexes_matrix[i] = 0

    return first_positive_index_matrix, remaining_positive_indexes_matrix


In [16]:
mat = torch.randint(0,2,(4,4))
mat

tensor([[1, 1, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 1, 0, 1]])

In [19]:
split_matrix(mat)

(tensor([[1, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0]]),
 tensor([[0, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 1]]))

In [1]:
import numpy as np

In [2]:
i = np.arange(2,6)
i
    

array([2, 3, 4, 5])

In [5]:
epoch = 6

In [6]:
if epoch in i:
    print(f'{epoch}')